### ISSUE TITLE
Memory usage of DualHybrid attack

### ISSUE THREAD

**Issue by ludopulles** [malb/lattice-estimator#88]
The current estimation for the memory usage in the DualHybrid attack, is equal to the time of the [FFT solver :link: ](https://github.com/malb/lattice-estimator/blob/main/estimator/lwe_dual.py#L238). However, I have some questions regarding the time and memory costs.
1) Shouldn't the memory usage of the lattice sieve be taken into account? That is, [the number of dual vectors `N` :link:](https://github.com/malb/lattice-estimator/blob/main/estimator/lwe_dual.py#L165) should somehow be taken into account for the memory. For example, the below code example suggests a 1:1 ratio between runtime and memory, whereas the FFT table is much smaller than the runtime:

```sage
from estimator import *
from estimator.lwe_dual import DualHybrid
from estimator.cost import Cost

Cost.register_impermanent(rop=True,mem=False,red=True,beta=False,delta=False,m=True,d=False,zeta=False,t=False)
DualHybrid.cost(LWE.exhaustive_search, schemes.Kyber512, 400, 22, 0, 80, log_level=1)

```
Output: `rop: ≈2^148.2, mem: ≈2^148.1, m: 510, β: 400, t: 80, d: 1000, ↻: 1`.

2) By sequentially performing the FFT solver (with an in-place FFT) for `size` many enumeration targets, leads instead to a memory cost of `size_fft` instead of `size * (m + t * size_fft)`, if you assume a score entry in the FFT table is 1 unit of memory.
3) I currently, do not understand the origin of the time-cost `size * m` in the FFT solver. Using [[Sec.5.2, MATZOV'22] :link:](https://zenodo.org/records/6412487), the updating of the "initial" FFT table can be reduced to an amortized cost of `4N` additions, when iterating over all the `size` possible enumeration guesses. That would lead to a total runtime cost of `4 * N * size` for initializing all the tables, instead of the naïve `t * N * size`, where `t` is the number of secret coordinates to guess mod 2.

**Comment by blowfish880** [comment]
It's been a while since I looked at the code, so the following is on a "as far as I can tell right now" basis:

1. Technically, yes. But the reduction models do not consider memory cost. One could add the number of vectors `N` to the memory cost, but compared to the cost of the FFT solver this seems negligible.

2. I agree, this is incorrect in the code. I think, this should be along the lines of `t * m + size_fft` if following [GuoJoh21] as claimed in the comment. See discussion on page 47 of [GuoJoh21].

3. As noted in the comment, this piece of code follows [GuoJoh21] and was written before [MATZOV'22] was published. Accordingly, this trick is not implemented.

As you pointed out the mistakes (many thanks!) I would offer you the chance to submit fixes. I would be happy to review your PR.
